function run3(){
var fs=require('fs');
var p='school-erp.html';
var t=fs.readFileSync(p,'utf8');
if(t.indexOf('erpSliderRun')!==-1){console.log('js exists');return;}
var oldJs='<script src="assets/js/main.js"></script>';
var newJs='<script src="assets/js/main.js"></script>\n    <script>\n    function erpSliderRun(){\n      var imgs=["01-student-dashboard.png","02-teacher-timetable.png","03-student-profile.png","04-parent-attendance.png","05-parent-exams.png"];\n      var caps=["Student Dashboard","Teacher Timetable","Student Profile","Parent Attendance","Parent Exams"];\n      var base="assets/img/school-erp/";\n      var i=0;\n      var main=document.getElementById("erpMainImg");\n      if(!main){return;}\n      var cap=document.getElementById("erpCaption");\n      var cnt=document.getElementById("erpCounter");\n      var dots=document.getElementById("erpDots");\n      var thumbs=document.getElementById("erpThumbs");\n      var timer=null;\n      var k=0;\n      dots.innerHTML="";\n      for(k=0;k<imgs.length;k++){\n        (function(idx){\n          var b=document.createElement("button");\n          b.setAttribute("aria-label","Go to "+(idx+1));\n          b.onclick=function(){show(idx);reset();};\n          dots.appendChild(b);\n        })(k);\n      }\n      function show(n){\n        if(n<0){n=imgs.length-1;}\n        if(n>=imgs.length){n=0;}\n        i=n;\n        main.src=base+imgs[i];\n        cap.textContent=caps[i];\n        cnt.textContent=(i+1)+" / "+imgs.length;\n        var d=dots.children;\n        for(var j=0;j<d.length;j++){d[j].className=(j===i)?"active":"";}\n        if(thumbs){var ths=thumbs.querySelectorAll("img");for(var m=0;m<ths.length;m++){ths[m].className=(m===i)?"active":"";}}\n      }\n      function reset(){if(timer){clearInterval(timer);}timer=setInterval(function(){show(i+1);},5000);}\n      document.getElementById("erpNext").onclick=function(){show(i+1);reset();};\n      document.getElementById("erpPrev").onclick=function(){show(i-1);reset();};\n      if(thumbs){var ths2=thumbs.querySelectorAll("img");for(var a=0;a<ths2.length;a++){(function(idx){ths2[idx].onclick=function(){show(idx);reset();};})(a);}}\n      var sx=0;\n      main.addEventListener("touchstart",function(e){sx=e.touches[0].clientX;},{passive:true});\n      main.addEventListener("touchend",function(e){var dx=e.changedTouches[0].clientX-sx;if(dx<-40){show(i+1);reset();}if(dx>40){show(i-1);reset();}},{passive:true});\n      var lb=document.getElementById("erpLightbox");\n      var lbImg=document.getElementById("erpLbImg");\n      main.onclick=function(){lbImg.src=base+imgs[i];lb.classList.add("open");};\n      document.getElementById("erpLbClose").onclick=function(){lb.classList.remove("open");};\n      lb.onclick=function(e){if(e.target===lb){lb.classList.remove("open");}};\n      show(0);reset();\n    }\n    if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",erpSliderRun);}else{erpSliderRun();}\n    </script>';
t=t.split(oldJs).join(newJs);
fs.writeFileSync(p,t,'utf8');
console.log('js added');}
run3();